-- 코드를 입력하세요
SELECT gu.USER_ID, gu.NICKNAME, SUM(gb.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD gb JOIN USED_GOODS_USER gu
 ON gb.WRITER_ID = gu.USER_ID
WHERE gb.STATUS = 'DONE'
GROUP BY 1
HAVING TOTAL_SALES >= 700000
ORDER BY 3