-- 코드를 입력하세요
SELECT DISTINCT(cc.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR cc 
 JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ch
 ON cc.CAR_ID = ch.CAR_ID
WHERE ch.START_DATE >= '2022-10-01'
 AND cc.CAR_TYPE = '세단'
ORDER BY 1 DESC