-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(bs.SALES) AS TOTAL_SALES
FROM BOOK b
 LEFT JOIN BOOK_SALES bs 
  ON b.BOOK_ID = bs.BOOK_ID
WHERE bs.SALES_DATE >= '2022-01-01' AND bs.SALES_DATE < '2022-02-01'
GROUP BY 1
ORDER BY 1
 